name: Deploy Angular App to Local Machine

on:
  push:
    branches:
      - master  # Or whichever branch you want to trigger deployment

jobs:
  deploy:
    runs-on: self-hosted  # This uses your registered runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set to your Angular project's required Node version

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build -- --output-path=dist

      - name: Deploy to D:/test
        run: |
          if not exist "D:\test" mkdir "D:\test"
          xcopy /E /I /Y dist\* D:\test\
