name: Deploy Angular App to Local Machine

on:
  push:
    branches:
      - master  # Or whichever branch you want to trigger deployment

jobs:
  deploy:
    runs-on: self-hosted  # This uses your registered runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to D:/test
        run: |
          if (-Not (Test-Path "D:\test")) {
            New-Item -ItemType Directory -Path "D:\test"
          }
          Copy-Item -Path "dist\*" -Destination "D:\test" -Recurse -Force
