name: Deploy Angular App to Local Machine

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted  # Your registered self-hosted runner (Windows)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to D:/test
        shell: powershell  # Use PowerShell Core (or use `powershell` for Windows PowerShell)
        run: |
          if (-Not (Test-Path "D:\test")) {
            New-Item -ItemType Directory -Path "D:\test"
          }
          Copy-Item -Path ".\dist\*"*
